import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './styles/styles.css'
import './styles/enhancements.css'
import './styles/brand.css'
import './styles/restaurant-polish.css'
import './styles/gallery-enhanced.css'
import './styles/premium-pages.css'
import './styles/liquid-glass.css'
import './styles/fresco-editorial.css'
import './styles/footer-social-sketches.css'
import './styles/about-wow.css'
import './styles/final-restaurant-polish.css'
import './styles/bar-effects.css'
import './styles/royal-blog.css'
import './styles/home-iconify-illustrations.css'
import './styles/final-home-luxury.css'
import './styles/mobile-qa.css'
import './styles/final-cinematic-menu.css'
import './styles/bar-clean-fix.css'
import './styles/bar-single-carousel.css'
import './styles/menu-drinks-polish.css'
import './styles/menu-spacing-repair.css'
import './styles/menukit-downloads.css'
import './styles/menu-navigation-repair.css'
import './styles/responsive-final-qa.css'
import './styles/menu-kit-hero-ux.css'
import './styles/mobile-production-fixes.css'
import './styles/mobile-final-hardening.css'
import './styles/home-mobile-final.css'
import './styles/desktop-final-polish.css'
import './styles/mobile-compact-final.css'
import './styles/header-scrolltop-final.css'
import './styles/home-mobile-centered-hero.css'
import './styles/mobile-image-safety-final.css'
import './styles/mobile-alignment-final.css'
import './styles/mobile-device-universal.css'
import './styles/mobile-home-meta-border-fix.css'
import './styles/mobile-home-first-impression-final.css'
import './styles/mobile-home-meta-row-final.css'
import './styles/final-release-polish.css'
import './styles/home-hero-header-final.css'
import './styles/home-dish-border-cleanup.css'
import './styles/home-hero-minimal-final.css'
import './styles/home-hero-layout-final.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>,
)
