import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CalendarDays, Check, Clock3, GlassWater, MapPin, Phone, UsersRound, UtensilsCrossed } from 'lucide-react'
import { gallery, hours, images, menu, site, testimonials } from './data'

export function SEO({ title, description }) {
  useEffect(() => {
    document.title = `${title} | ${site.name}`
    const tag = document.querySelector('meta[name="description"]')
    if (tag) tag.setAttribute('content', description)
  }, [title, description])
  return null
}

export function PageHero({ eyebrow, title, text, image = images.interior, compact = false }) {
  return (
    <section className={`page-hero ${compact ? 'compact' : ''}`} style={{ '--page-image': `url(${image})` }}>
      <div className="page-hero-overlay"/>
      <div className="shell page-hero-content">
        <p className="eyebrow light">{eyebrow}</p>
        <h1>{title}</h1>
        {text && <p className="page-hero-copy">{text}</p>}
      </div>
    </section>
  )
}

function SectionHeading({ eyebrow, title, text, light = false, align = 'left' }) {
  return <div className={`section-heading ${light ? 'light' : ''} ${align === 'center' ? 'center' : ''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>
}

function MenuPreview() {
  const featured = [menu.Starters[0], menu.Mains[0], menu['Steak & Seafood'][0], menu.Desserts[0]]
  const pics = [images.food, images.pasta, images.steak, images.dessert]
  return <div className="dish-grid">{featured.map((item, i) => <article className="dish-card" key={item[0]}><img src={pics[i]} alt={item[0]} loading="lazy"/><div className="dish-card-body"><div className="dish-title"><h3>{item[0]}</h3><span>{item[2]}</span></div><p>{item[1]}</p></div></article>)}</div>
}

export function Home() {
  return <>
    <SEO title="Restaurant & Bar" description="Aurelia is a premium restaurant and bar demo experience with dining, cocktails, private events, catering and reservations."/>
    <section className="home-hero" style={{ '--hero-image': `url(${images.hero})` }}>
      <div className="hero-shade"/>
      <div className="hero-grain"/>
      <div className="shell hero-content">
        <p className="eyebrow light">An evening worth remembering</p>
        <h1>{site.name}</h1>
        <p className="hero-subtitle">{site.tagline}</p>
        <div className="hero-actions"><Link to="/menu" className="button button-cream">View Menu</Link><Link to="/booking" className="button button-outline-light">Reserve a Table</Link></div>
      </div>
      <div className="hero-foot shell"><span>Fine food • craft cocktails • private occasions</span><span className="scroll-cue">Scroll to discover ↓</span></div>
    </section>

    <section className="section intro-section"><div className="shell split-grid image-first"><div className="image-frame tall"><img src={images.interior} alt="Warm modern restaurant dining room"/></div><div className="split-copy"><SectionHeading eyebrow="Welcome to Aurelia" title="Crafted with intention. Served with warmth." text="Aurelia is a fictional premium restaurant concept created for this demo. The experience combines a refined dining room, expressive seasonal cooking and a destination bar — all designed around the pleasure of gathering."/><div className="signature-line"><span>Kitchen-led dining</span><span>Late-night bar</span><span>Private events</span></div><Link className="text-link large" to="/about">Discover our story <ArrowRight size={18}/></Link></div></div></section>

    <section className="section section-dark"><div className="shell"><SectionHeading light eyebrow="From the kitchen" title="A menu made for the moment." text="Seasonal plates, familiar ingredients and confident flavours. Demo selections are easy to replace when the final menu is supplied."/><MenuPreview/><div className="center-action"><Link to="/menu" className="button button-gold">Explore Full Menu</Link></div></div></section>

    <section className="experience-grid"><article className="experience-card" style={{ '--bg': `url(${images.food})` }}><div/><div className="experience-copy"><p className="eyebrow light">The kitchen</p><h2>Food with a point of view.</h2><p>Season-led cooking, polished technique and plates designed to share the table.</p><Link to="/menu">Explore dining <ArrowRight size={17}/></Link></div></article><article className="experience-card" style={{ '--bg': `url(${images.bar})` }}><div/><div className="experience-copy"><p className="eyebrow light">The bar</p><h2>Stay for one more.</h2><p>Classic cocktails, modern signatures and a room that gets better as the evening settles in.</p><Link to="/visiting-hours">Plan your visit <ArrowRight size={17}/></Link></div></article></section>

    <section className="section"><div className="shell split-grid"><div className="split-copy"><SectionHeading eyebrow="Private gatherings" title="Your occasion, beautifully hosted." text="From milestone birthdays to intimate receptions and corporate dinners, our banquet concept pairs elevated hospitality with flexible event planning."/><div className="icon-points"><span><UsersRound/> Private celebrations</span><span><GlassWater/> Cocktail receptions</span><span><UtensilsCrossed/> Seated dinners</span></div><Link className="button button-dark" to="/banquet">Explore Banquet Facility</Link></div><div className="image-stack"><img className="stack-main" src={images.banquet} alt="Elegant private dining setup" loading="lazy"/><img className="stack-small" src={images.table} alt="Restaurant table setting" loading="lazy"/></div></div></section>

    <section className="section catering-band"><div className="shell catering-inner"><div><p className="eyebrow light">Aurelia beyond our doors</p><h2>Catering with the same attention to detail.</h2></div><p>Thoughtful menus and polished service for private, social and corporate occasions.</p><Link to="/catering" className="button button-cream">Explore Catering</Link></div></section>

    <section className="section gallery-home"><div className="shell"><SectionHeading eyebrow="A glimpse inside" title="Food, atmosphere, and everything between."/><div className="gallery-strip">{gallery.slice(0, 5).map((src, i) => <img key={src} src={src} alt={`Aurelia restaurant atmosphere ${i + 1}`} loading="lazy"/>)}</div><div className="center-action"><Link className="text-link large" to="/gallery">View the gallery <ArrowRight size={18}/></Link></div></div></section>

    <section className="section hours-home section-warm"><div className="shell split-grid"><div><SectionHeading eyebrow="Plan your evening" title="Dining room & bar hours."/><p className="muted">These hours are demo placeholders and can be replaced instantly once the restaurant schedule is confirmed.</p><Link className="text-link large" to="/visiting-hours">Full visiting information <ArrowRight size={18}/></Link></div><div className="hours-table"><div className="hours-head"><span>Day</span><span>Dining</span><span>Bar</span></div>{hours.map(row => <div className="hours-row" key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div></div></section>

    <section className="section testimonial-section"><div className="shell testimonial-feature"><p className="quote-mark">“</p><blockquote>{testimonials[0][0]}</blockquote><p>— {testimonials[0][1]}</p><div className="testimonial-mini">{testimonials.slice(1).map(([quote, name]) => <article key={name}><p>{quote}</p><span>{name}</span></article>)}</div></div></section>

    <section className="reservation-banner" style={{ '--reservation-image': `url(${images.table})` }}><div/><div className="shell reservation-content"><p className="eyebrow light">Join us</p><h2>Your table awaits.</h2><p>Choose your date, time and party size. No account required.</p><Link to="/booking" className="button button-cream">Reserve a Table</Link></div></section>

    <section className="section"><div className="shell contact-teaser"><div><p className="eyebrow">Find us</p><h2>Come for dinner. Stay for the evening.</h2></div><div className="contact-teaser-details"><p><MapPin/> {site.address}</p><p><Phone/> {site.phone}</p><Link className="text-link" to="/contact">Contact & directions <ArrowRight size={17}/></Link></div></div></section>
  </>
}

export function About() {
  return <><SEO title="About" description="Discover the story, philosophy and hospitality behind the Aurelia restaurant and bar demo."/><PageHero eyebrow="Our story" title="A restaurant built around the table." text="A premium concept where food, room and service move together." image={images.interior}/><section className="section"><div className="shell split-grid"><div className="image-frame"><img src={images.chef} alt="Chef working in the kitchen"/></div><div className="split-copy"><SectionHeading eyebrow="Our philosophy" title="Good restaurants create more than good meals." text="Aurelia is designed as a believable client-ready concept rather than a generic template. The story, cuisine and team details shown here are placeholders until the final brand direction is confirmed."/><p>Our demo philosophy is simple: cook with seasonality, pour with personality, serve with warmth, and create a room people want to return to.</p><div className="stats"><div><strong>Season-led</strong><span>Menus designed to evolve</span></div><div><strong>Hospitality-first</strong><span>Warm, polished service</span></div></div></div></div></section><section className="section section-warm"><div className="shell"><SectionHeading align="center" eyebrow="What we value" title="The details shape the experience."/><div className="value-grid"><article><span>01</span><h3>Ingredient integrity</h3><p>Clear flavours, quality produce and thoughtful sourcing.</p></article><article><span>02</span><h3>Room with energy</h3><p>A dining room and bar designed to shift naturally through the evening.</p></article><article><span>03</span><h3>Human hospitality</h3><p>Attentive without being formal, polished without feeling distant.</p></article></div></div></section><section className="section"><div className="shell split-grid reverse-mobile"><div className="split-copy"><SectionHeading eyebrow="Restaurant + bar" title="Two moods. One evening." text="Start with dinner, continue at the bar, or meet friends for cocktails first. Aurelia is conceived as one connected hospitality experience."/><Link to="/booking" className="button button-dark">Book a Table</Link></div><div className="image-frame wide"><img src={images.bar} alt="Moody cocktail bar interior"/></div></div></section></>
}

export function MenuPage() {
  const [active, setActive] = useState('Starters')
  const categories = Object.keys(menu)
  return <><SEO title="Menu" description="Explore demo starters, mains, steak and seafood, desserts, cocktails and seasonal selections."/><PageHero eyebrow="Eat & drink" title="The menu." text="Seasonal cooking, familiar ingredients, and a bar programme made for the evening." image={images.food}/><section className="section menu-page"><div className="shell"><div className="menu-tabs" role="tablist" aria-label="Menu categories">{categories.map(cat => <button key={cat} className={active === cat ? 'active' : ''} onClick={() => setActive(cat)}>{cat}</button>)}</div><div className="menu-layout"><div><p className="eyebrow">Currently viewing</p><h2>{active}</h2><p className="muted">Demo menu content and pricing. Replace with final restaurant menu before production.</p></div><div className="menu-list">{menu[active].map(([name, description, price]) => <article className="menu-line" key={name}><div><h3>{name}</h3><p>{description}</p></div><span>{price}</span></article>)}</div></div><div className="menu-note"><span>Dietary needs?</span><p>Please advise the restaurant of allergies or dietary restrictions when booking.</p></div></div></section><section className="menu-image-break" style={{ '--bg': `url(${active === 'Cocktails' ? images.cocktail : images.pasta})` }}><div/><div><p className="eyebrow light">From the kitchen & bar</p><h2>Made to stay awhile.</h2></div></section></>
}

export function Banquet() {
  return <><SEO title="Banquet Facility" description="Explore Aurelia's demo banquet and private event experience for celebrations, receptions and corporate dinners."/><PageHero eyebrow="Private events" title="Celebrate beautifully." text="A flexible private dining concept for meaningful occasions, designed around your guest list." image={images.banquet}/><section className="section"><div className="shell split-grid"><div className="split-copy"><SectionHeading eyebrow="Banquet facility" title="A room ready for your occasion." text="This page is structured to sell the venue once final capacity, floor plan, packages and amenities are supplied."/><div className="check-list"><span><Check/> Birthdays & anniversaries</span><span><Check/> Corporate dinners</span><span><Check/> Cocktail receptions</span><span><Check/> Showers & family celebrations</span><span><Check/> Custom menu options</span><span><Check/> Dedicated event contact</span></div><Link to="/contact" className="button button-dark">Request Event Information</Link></div><div className="image-frame tall"><img src={images.table} alt="Private event dining tables"/></div></div></section><section className="section section-dark"><div className="shell"><SectionHeading light align="center" eyebrow="Event possibilities" title="Sized around your gathering."/><div className="event-grid"><article><UsersRound/><h3>Intimate dinners</h3><p>Private seated experiences for smaller guest lists.</p><strong>Capacity TBD</strong></article><article><GlassWater/><h3>Receptions</h3><p>Flexible cocktail-style layouts with passed bites and bar service.</p><strong>Capacity TBD</strong></article><article><UtensilsCrossed/><h3>Full celebrations</h3><p>Custom menus, room planning and coordinated hospitality.</p><strong>Capacity TBD</strong></article></div></div></section><section className="section"><div className="shell"><SectionHeading eyebrow="The setting" title="A space that photographs as beautifully as it hosts."/><div className="gallery-strip banquet-gallery">{[images.banquet, images.interior, images.table].map((src,i)=><img src={src} key={src} alt={`Banquet venue view ${i+1}`}/>)}</div></div></section></>
}

export function Catering() {
  return <><SEO title="Catering" description="Discover Aurelia's demo catering service for private events, corporate gatherings and celebrations."/><PageHero eyebrow="Bring Aurelia to you" title="Catering, considered." text="Food, service and presentation designed to travel beyond our dining room." image={images.catering}/><section className="section"><div className="shell"><SectionHeading align="center" eyebrow="Occasions" title="From boardroom lunches to milestone celebrations."/><div className="value-grid four"><article><span>01</span><h3>Corporate</h3><p>Meetings, launches and team dinners with flexible service.</p></article><article><span>02</span><h3>Social</h3><p>Birthdays, showers and family occasions made effortless.</p></article><article><span>03</span><h3>Reception</h3><p>Passed bites, grazing tables and cocktail-forward events.</p></article><article><span>04</span><h3>Custom</h3><p>Menus tailored to your event style, scale and dietary needs.</p></article></div></div></section><section className="section section-warm"><div className="shell split-grid"><div className="image-frame wide"><img src={images.food} alt="Catered food spread"/></div><div className="split-copy"><SectionHeading eyebrow="Service styles" title="Built around how you want to host." text="Use this section later for real package tiers, minimums and service inclusions. For the demo, it communicates capability without inventing permanent policy."/><div className="check-list"><span><Check/> Drop-off catering</span><span><Check/> Staffed buffet service</span><span><Check/> Plated dinners</span><span><Check/> Cocktail reception service</span></div><Link to="/contact" className="button button-dark">Start a Catering Inquiry</Link></div></div></section></>
}

export function Gallery() {
  const [filter, setFilter] = useState('All')
  const items = useMemo(() => gallery.map((src,i)=>({src, type:['Dining','Food','Bar','Events'][i%4]})),[])
  const shown = filter === 'All' ? items : items.filter(x=>x.type===filter)
  return <><SEO title="Gallery" description="Explore the Aurelia demo gallery featuring food, dining, bar atmosphere and private events."/><PageHero compact eyebrow="Gallery" title="Inside Aurelia." text="A visual look at the food, room, bar and atmosphere." image={images.bar}/><section className="section"><div className="shell"><div className="gallery-filters">{['All','Dining','Food','Bar','Events'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="gallery-masonry">{shown.map((item,i)=><figure key={`${item.src}-${i}`}><img src={item.src} alt={`${item.type} at Aurelia`} loading="lazy"/><figcaption>{item.type}</figcaption></figure>)}</div></div></section></>
}

export function VisitingHours() {
  return <><SEO title="Visiting Hours" description="View demo dining room and bar hours, location details and reservation information for Aurelia."/><PageHero eyebrow="Plan your visit" title="Hours & location." text="Everything you need before you arrive." image={images.interior}/><section className="section"><div className="shell visit-grid"><div><SectionHeading eyebrow="When to visit" title="Dining room & bar."/><div className="hours-table large"><div className="hours-head"><span>Day</span><span>Dining room</span><span>Bar</span></div>{hours.map(row=><div className="hours-row" key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</div>)}</div><p className="demo-note">Demo hours shown. Final schedule will be updated after client confirmation.</p></div><aside className="visit-card"><MapPin/><h3>{site.address}</h3><p>Use the final address here for live map and directions integration.</p><hr/><Phone/><a href={`tel:${site.phone.replace(/[^0-9+]/g,'')}`}>{site.phone}</a><hr/><Clock3/><p>Reservations recommended for dinner service.</p><Link className="button button-gold" to="/booking">Reserve a Table</Link></aside></div></section></>
}

export function Booking() {
  const [sent,setSent]=useState(false)
  const submit=e=>{e.preventDefault();setSent(true)}
  return <><SEO title="Online Booking" description="Reserve a demo table at Aurelia by selecting date, time, guest count and contact information."/><PageHero compact eyebrow="Reservations" title="Your table awaits." text="Submit your preferred date and time and we'll take it from there." image={images.table}/><section className="section booking-section"><div className="shell booking-grid"><div><SectionHeading eyebrow="Book a table" title="Plan your evening." text="This demo form validates required fields in the browser. A production booking platform or form endpoint can be connected later."/><div className="booking-notes"><span><CalendarDays/> Choose your preferred date</span><span><UsersRound/> Parties of all sizes welcome to inquire</span><span><Phone/> For urgent changes, call the restaurant</span></div></div><form className="booking-form" onSubmit={submit}>{sent ? <div className="form-success"><Check size={36}/><h3>Reservation request received.</h3><p>This is a front-end demo confirmation. No live reservation was submitted.</p><button type="button" className="button button-dark" onClick={()=>setSent(false)}>Make Another Request</button></div> : <><div className="form-grid"><label>Full name<input name="name" required autoComplete="name"/></label><label>Email<input type="email" name="email" required autoComplete="email"/></label><label>Phone<input type="tel" name="phone" required autoComplete="tel"/></label><label>Guests<select name="guests" required defaultValue="2"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7+</option></select></label><label>Date<input type="date" name="date" required/></label><label>Time<select name="time" required defaultValue=""><option value="" disabled>Select a time</option><option>5:00 PM</option><option>5:30 PM</option><option>6:00 PM</option><option>6:30 PM</option><option>7:00 PM</option><option>7:30 PM</option><option>8:00 PM</option><option>8:30 PM</option><option>9:00 PM</option></select></label><label className="full">Special requests<textarea name="notes" rows="4" placeholder="Allergies, accessibility needs, celebration details..."/></label></div><button className="button button-gold full-button" type="submit">Request Reservation</button><p className="form-fineprint">Demo only — submitting this form does not create a real reservation.</p></>}</form></div></section></>
}

export function MenuKit() {
  return <><SEO title="Menu Kit" description="A flexible placeholder page for the client's requested Menu Kit content."/><PageHero compact eyebrow="Menu Kit" title="A flexible space for the final brief." text="The client requested a dedicated Menu Kit page but has not yet defined its exact purpose." image={images.food}/><section className="section"><div className="shell narrow"><SectionHeading eyebrow="Purpose pending confirmation" title="Designed now. Easy to adapt later." text="Rather than inventing permanent functionality, this page provides a polished foundation that can become a downloadable menu pack, event menu resource, media kit or another client-defined experience once clarified."/><div className="kit-grid"><article><span>01</span><h3>Digital menu collection</h3><p>Could house PDF menus, seasonal menus or print-ready resources.</p></article><article><span>02</span><h3>Event menu resource</h3><p>Could present banquet, catering and private dining menu options.</p></article><article><span>03</span><h3>Custom client direction</h3><p>The structure can be repurposed quickly after William confirms the intended meaning.</p></article></div><div className="demo-callout"><strong>Demo note</strong><p>No download or complex functionality has been invented yet. This protects the scope until the requirement is confirmed.</p></div></div></section></>
}

export function Contact() {
  const [sent,setSent]=useState(false)
  return <><SEO title="Contact" description="Contact Aurelia restaurant and bar for general, banquet, catering and reservation inquiries."/><PageHero compact eyebrow="Get in touch" title="Contact Aurelia." text="Questions, events, catering or general inquiries — start here." image={images.interior}/><section className="section"><div className="shell contact-grid"><div><SectionHeading eyebrow="Visit & connect" title="We'd love to hear from you."/><div className="contact-list"><div><MapPin/><span><small>Address</small>{site.address}</span></div><div><Phone/><span><small>Phone</small><a href={`tel:${site.phone.replace(/[^0-9+]/g,'')}`}>{site.phone}</a></span></div><div><Clock3/><span><small>Email</small><a href={`mailto:${site.email}`}>{site.email}</a></span></div></div><div className="map-placeholder"><MapPin size={34}/><span>Interactive map will connect to the final restaurant address.</span></div></div><form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}>{sent?<div className="form-success"><Check size={34}/><h3>Message captured.</h3><p>This is a demo confirmation. Connect the production form endpoint before launch.</p></div>:<><label>Name<input required name="name" autoComplete="name"/></label><label>Email<input required type="email" name="email" autoComplete="email"/></label><label>Inquiry type<select name="type"><option>General inquiry</option><option>Banquet / private event</option><option>Catering</option><option>Reservation question</option></select></label><label>Message<textarea required rows="6" name="message"/></label><button className="button button-dark" type="submit">Send Inquiry</button></>}</form></div></section></>
}

export function NotFound() {
  return <section className="not-found"><SEO title="Page Not Found" description="The requested page could not be found."/><div><p className="eyebrow">404</p><h1>This table isn't available.</h1><p>The page you're looking for may have moved.</p><Link to="/" className="button button-gold">Return Home</Link></div></section>
}
